services:
  django_server:
    build: .
    container_name: django_server
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - pgdb_server
    
  pgdb_server:
    image: postgres
    container_name: pgdb_server
    environment:
      - POSTGRES_DB=thebgacademy
      - POSTGRES_USER=BGAdmin
      - POSTGRES_PASSWORD=i-am-a-random-password
    volumes:
      - pgdata:/var/lib/postgresql/data/

volumes:
  pgdata: